# Generated by Django 4.2.15 on 2024-08-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
